### ISSUE TITLE
Change current license AGPL 3 to MIT

### ISSUE THREAD

**Issue by Syndesi** [ember-nexus/reference-dataset#52]
During license changes initiated by https://github.com/ember-nexus/governance/issues/3 this repository was marked for license change as well. However as this repository is used as a dependency for other softwares, the usage of `AGPL-3` in the first place was not intended. Instead the license should be changed to `MIT`.

While this is an important change, this does **not** affect functionality as defined in the [semantic versioning specification](https://semver.org/#spec-item-8):

> Major version X (X.y.z | X > 0) MUST be incremented if **any backward incompatible changes are introduced to the public API**. It MAY also include minor and patch level changes. Patch and minor versions MUST be reset to 0 when major version is incremented.

Therefore this change will be rolled out with the next release, regardless of its type (major / minor / patch).

### Tasks

- [x] Change the license in all files:
  - [x] Readme, including shields.
  - [x] Readme in documentation, including shields.
  - [x] `LICENSE`
- [ ] Create and publish new release.
